export type Role = 'OWNER' | 'ADMIN' | 'STAFF';

export type Permission =
  | 'BUSINESS_READ'
  | 'BUSINESS_UPDATE'
  | 'MEMBERS_READ'
  | 'MEMBERS_MANAGE'
  | 'PRODUCT_READ'
  | 'PRODUCT_CREATE'
  | 'PRODUCT_UPDATE'
  | 'PRODUCT_ARCHIVE'
  | 'INVENTORY_READ'
  | 'INVENTORY_ADJUST'
  | 'CUSTOMER_READ'
  | 'CUSTOMER_CREATE'
  | 'CUSTOMER_UPDATE'
  | 'SALE_CREATE'
  | 'SALE_CANCEL'
  | 'INVOICE_READ'
  | 'INVOICE_CREATE'
  | 'INVOICE_ISSUE'
  | 'INVOICE_PAY'
  | 'INVOICE_REFUND'
  | 'EXPENSE_READ'
  | 'EXPENSE_CREATE'
  | 'EXPENSE_UPDATE'
  | 'PROFIT_READ'
  | 'TAX_READ'
  | 'REPORT_READ'
  | 'REPORT_EXPORT'
  | 'AI_FINANCIAL_READ'
  | 'AUDIT_READ';

// Central mapping of default permissions per role
export const ROLE_PERMISSIONS: Record<Role, Set<Permission>> = {
  OWNER: new Set<Permission>([
    'BUSINESS_READ', 'BUSINESS_UPDATE',
    'MEMBERS_READ', 'MEMBERS_MANAGE',
    'PRODUCT_READ', 'PRODUCT_CREATE', 'PRODUCT_UPDATE', 'PRODUCT_ARCHIVE',
    'INVENTORY_READ', 'INVENTORY_ADJUST',
    'CUSTOMER_READ', 'CUSTOMER_CREATE', 'CUSTOMER_UPDATE',
    'SALE_CREATE', 'SALE_CANCEL',
    'INVOICE_READ', 'INVOICE_CREATE', 'INVOICE_ISSUE', 'INVOICE_PAY', 'INVOICE_REFUND',
    'EXPENSE_READ', 'EXPENSE_CREATE', 'EXPENSE_UPDATE',
    'PROFIT_READ', 'TAX_READ',
    'REPORT_READ', 'REPORT_EXPORT',
    'AI_FINANCIAL_READ', 'AUDIT_READ'
  ]),
  ADMIN: new Set<Permission>([
    'BUSINESS_READ', 'BUSINESS_UPDATE',
    'MEMBERS_READ', 'MEMBERS_MANAGE',
    'PRODUCT_READ', 'PRODUCT_CREATE', 'PRODUCT_UPDATE', 'PRODUCT_ARCHIVE',
    'INVENTORY_READ', 'INVENTORY_ADJUST',
    'CUSTOMER_READ', 'CUSTOMER_CREATE', 'CUSTOMER_UPDATE',
    'SALE_CREATE', 'SALE_CANCEL',
    'INVOICE_READ', 'INVOICE_CREATE', 'INVOICE_ISSUE', 'INVOICE_PAY', 'INVOICE_REFUND',
    'EXPENSE_READ', 'EXPENSE_CREATE', 'EXPENSE_UPDATE',
    'PROFIT_READ', 'TAX_READ',
    'REPORT_READ', 'REPORT_EXPORT',
    'AI_FINANCIAL_READ', 'AUDIT_READ'
    // Configurable permissions, but cannot exceed owner or modify owner
  ]),
  STAFF: new Set<Permission>([
    'BUSINESS_READ',
    'MEMBERS_READ',
    'PRODUCT_READ', 'PRODUCT_CREATE', 'PRODUCT_UPDATE',
    'INVENTORY_READ',
    'CUSTOMER_READ', 'CUSTOMER_CREATE', 'CUSTOMER_UPDATE',
    'SALE_CREATE',
    'INVOICE_READ', 'INVOICE_CREATE', 'INVOICE_PAY',
    'EXPENSE_READ', 'EXPENSE_CREATE'
    // Staff must not retrieve profitability, margin, tax-liability, debt, loan, or business-value information.
    // Excludes: MEMBERS_MANAGE, PRODUCT_ARCHIVE, INVENTORY_ADJUST, SALE_CANCEL, INVOICE_ISSUE, INVOICE_REFUND, EXPENSE_UPDATE, PROFIT_READ, TAX_READ, REPORT_EXPORT, AI_FINANCIAL_READ, AUDIT_READ
  ])
};

export function hasPermission(role: Role, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.has(permission) ?? false;
}
