-- Additive purchasing, supplier, expense, GST allocation and journal-source migration.
CREATE TYPE "PurchaseBillStatus" AS ENUM ('DRAFT', 'RECEIVED', 'PARTIALLY_PAID', 'PAID', 'CANCELLED');
ALTER TABLE "Transaction" ADD COLUMN "reversalOfId" TEXT, ADD COLUMN "sourceId" TEXT, ADD COLUMN "sourceType" TEXT;

CREATE TABLE "Supplier" ("id" TEXT NOT NULL, "businessId" TEXT NOT NULL, "name" TEXT NOT NULL, "contactPerson" TEXT, "email" TEXT, "phone" TEXT, "gstin" TEXT, "pan" TEXT, "address" TEXT, "city" TEXT, "state" TEXT, "pincode" TEXT, "paymentTerms" TEXT DEFAULT 'DUE_ON_RECEIPT', "creditLimit" DECIMAL(15,2), "currentBalance" DECIMAL(15,2) NOT NULL DEFAULT 0, "archived" BOOLEAN NOT NULL DEFAULT false, "notes" TEXT, "createdById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Supplier_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PurchaseBill" ("id" TEXT NOT NULL, "businessId" TEXT NOT NULL, "supplierId" TEXT NOT NULL, "billNumber" TEXT NOT NULL, "supplierInvoiceNumber" TEXT, "status" "PurchaseBillStatus" NOT NULL DEFAULT 'RECEIVED', "billDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "dueDate" TIMESTAMP(3), "subtotal" DECIMAL(15,2) NOT NULL DEFAULT 0, "discountAmount" DECIMAL(15,2) NOT NULL DEFAULT 0, "taxAmount" DECIMAL(15,2) NOT NULL DEFAULT 0, "cgstAmount" DECIMAL(15,2) NOT NULL DEFAULT 0, "sgstAmount" DECIMAL(15,2) NOT NULL DEFAULT 0, "igstAmount" DECIMAL(15,2) NOT NULL DEFAULT 0, "totalAmount" DECIMAL(15,2) NOT NULL DEFAULT 0, "paidAmount" DECIMAL(15,2) NOT NULL DEFAULT 0, "balanceDue" DECIMAL(15,2) NOT NULL DEFAULT 0, "notes" TEXT, "idempotencyKey" TEXT, "createdById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PurchaseBill_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PurchaseBillItem" ("id" TEXT NOT NULL, "billId" TEXT NOT NULL, "productId" TEXT, "productNameSnapshot" TEXT NOT NULL, "skuSnapshot" TEXT, "unitSnapshot" TEXT, "quantity" DECIMAL(15,4) NOT NULL, "unitCost" DECIMAL(15,2) NOT NULL, "discount" DECIMAL(15,2) NOT NULL DEFAULT 0, "taxRate" DECIMAL(5,2) NOT NULL DEFAULT 0, "taxAmount" DECIMAL(15,2) NOT NULL DEFAULT 0, "lineSubtotal" DECIMAL(15,2) NOT NULL, "lineTotal" DECIMAL(15,2) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PurchaseBillItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PurchasePayment" ("id" TEXT NOT NULL, "businessId" TEXT NOT NULL, "billId" TEXT, "supplierId" TEXT NOT NULL, "amount" DECIMAL(15,2) NOT NULL, "paymentMethod" "PaymentMethod" NOT NULL DEFAULT 'BANK_TRANSFER', "paymentDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "reference" TEXT, "notes" TEXT, "idempotencyKey" TEXT, "createdById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PurchasePayment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ExpenseCategory" ("id" TEXT NOT NULL, "businessId" TEXT NOT NULL, "name" TEXT NOT NULL, "code" TEXT, "defaultAccountId" TEXT, "description" TEXT, "isTaxDeductible" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ExpenseCategory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Expense" ("id" TEXT NOT NULL, "businessId" TEXT NOT NULL, "expenseNumber" TEXT NOT NULL, "categoryId" TEXT, "accountId" TEXT NOT NULL, "supplierId" TEXT, "payeeName" TEXT NOT NULL, "amount" DECIMAL(15,2) NOT NULL, "taxRate" DECIMAL(5,2) NOT NULL DEFAULT 0, "taxAmount" DECIMAL(15,2) NOT NULL DEFAULT 0, "totalAmount" DECIMAL(15,2) NOT NULL, "paymentMethod" "PaymentMethod" NOT NULL DEFAULT 'BANK_TRANSFER', "paymentStatus" TEXT NOT NULL DEFAULT 'PAID', "expenseDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "reference" TEXT, "receiptUrl" TEXT, "notes" TEXT, "createdById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Expense_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PurchaseSequence" ("id" TEXT NOT NULL, "businessId" TEXT NOT NULL, "currentNumber" INTEGER NOT NULL DEFAULT 0, "prefix" TEXT NOT NULL DEFAULT 'BILL', "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PurchaseSequence_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ExpenseSequence" ("id" TEXT NOT NULL, "businessId" TEXT NOT NULL, "currentNumber" INTEGER NOT NULL DEFAULT 0, "prefix" TEXT NOT NULL DEFAULT 'EXP', "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ExpenseSequence_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "PurchaseBill_businessId_billNumber_key" ON "PurchaseBill"("businessId", "billNumber");
CREATE UNIQUE INDEX "PurchaseBill_businessId_idempotencyKey_key" ON "PurchaseBill"("businessId", "idempotencyKey");
CREATE UNIQUE INDEX "PurchasePayment_businessId_idempotencyKey_key" ON "PurchasePayment"("businessId", "idempotencyKey");
CREATE UNIQUE INDEX "ExpenseCategory_businessId_name_key" ON "ExpenseCategory"("businessId", "name");
CREATE UNIQUE INDEX "Expense_businessId_expenseNumber_key" ON "Expense"("businessId", "expenseNumber");
CREATE UNIQUE INDEX "PurchaseSequence_businessId_key" ON "PurchaseSequence"("businessId");
CREATE UNIQUE INDEX "ExpenseSequence_businessId_key" ON "ExpenseSequence"("businessId");
CREATE INDEX "Transaction_businessId_sourceType_sourceId_idx" ON "Transaction"("businessId", "sourceType", "sourceId");
CREATE INDEX "Transaction_reversalOfId_idx" ON "Transaction"("reversalOfId");
CREATE INDEX "Supplier_businessId_name_idx" ON "Supplier"("businessId", "name"); CREATE INDEX "Supplier_businessId_archived_idx" ON "Supplier"("businessId", "archived");
CREATE INDEX "PurchaseBill_businessId_status_idx" ON "PurchaseBill"("businessId", "status"); CREATE INDEX "PurchaseBill_businessId_billDate_idx" ON "PurchaseBill"("businessId", "billDate");
CREATE INDEX "PurchasePayment_businessId_paymentDate_idx" ON "PurchasePayment"("businessId", "paymentDate"); CREATE INDEX "Expense_businessId_expenseDate_idx" ON "Expense"("businessId", "expenseDate");

ALTER TABLE "Supplier" ADD CONSTRAINT "Supplier_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE; ALTER TABLE "Supplier" ADD CONSTRAINT "Supplier_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "PurchaseBill" ADD CONSTRAINT "PurchaseBill_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE; ALTER TABLE "PurchaseBill" ADD CONSTRAINT "PurchaseBill_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE RESTRICT; ALTER TABLE "PurchaseBill" ADD CONSTRAINT "PurchaseBill_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "PurchaseBillItem" ADD CONSTRAINT "PurchaseBillItem_billId_fkey" FOREIGN KEY ("billId") REFERENCES "PurchaseBill"("id") ON DELETE CASCADE; ALTER TABLE "PurchaseBillItem" ADD CONSTRAINT "PurchaseBillItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE SET NULL;
ALTER TABLE "PurchasePayment" ADD CONSTRAINT "PurchasePayment_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE; ALTER TABLE "PurchasePayment" ADD CONSTRAINT "PurchasePayment_billId_fkey" FOREIGN KEY ("billId") REFERENCES "PurchaseBill"("id") ON DELETE SET NULL; ALTER TABLE "PurchasePayment" ADD CONSTRAINT "PurchasePayment_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE RESTRICT; ALTER TABLE "PurchasePayment" ADD CONSTRAINT "PurchasePayment_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "ExpenseCategory" ADD CONSTRAINT "ExpenseCategory_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE; ALTER TABLE "ExpenseCategory" ADD CONSTRAINT "ExpenseCategory_defaultAccountId_fkey" FOREIGN KEY ("defaultAccountId") REFERENCES "Account"("id") ON DELETE SET NULL;
ALTER TABLE "Expense" ADD CONSTRAINT "Expense_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE; ALTER TABLE "Expense" ADD CONSTRAINT "Expense_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "ExpenseCategory"("id") ON DELETE SET NULL; ALTER TABLE "Expense" ADD CONSTRAINT "Expense_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE RESTRICT; ALTER TABLE "Expense" ADD CONSTRAINT "Expense_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE SET NULL; ALTER TABLE "Expense" ADD CONSTRAINT "Expense_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "PurchaseSequence" ADD CONSTRAINT "PurchaseSequence_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE; ALTER TABLE "ExpenseSequence" ADD CONSTRAINT "ExpenseSequence_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE;
